In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


In [4]:
print(tf.config.list_physical_devices('GPU'))

[]


In [13]:
a = tf.constant(10)
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [14]:
b = tf.constant(20)
print(a + b)

tf.Tensor(30, shape=(), dtype=int32)


In [6]:
v = tf.constant([1, 2, 3, 4])
print(v)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [12]:
m = tf.constant([[1, 2], [3, 4],[1,5]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]
 [1 5]], shape=(3, 2), dtype=int32)


In [15]:
t3=tf.constant([[[1,2],
                [3,4]],
                [[5,6],
                [7,8]]])
print(t3)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [16]:
a = tf.constant([10, 20, 20])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


In [10]:
v1 = tf.constant([1, 2, 3,8])
print(v+v1)

tf.Tensor([ 2  4  6 12], shape=(4,), dtype=int32)


In [17]:
import numpy as np
np_array = np.array([[1,2,3], [4,5,6]])

tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [19]:
v = tf.constant([1,2,3,4])
u= tf.constant([5,6,7,8])
print(v)
print(u)

print("Add :",tf.add(v,u))
print("subtract : ",tf.subtract(v,u))
print("multiply : ",tf.multiply(v,u))
print("divide : ",tf.divide(v,u))
print("floordiv : ",tf.math.floordiv(v,u))
print("power : ",tf.pow(v,u))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
Add : tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
subtract :  tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
multiply :  tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
divide :  tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)
floordiv :  tf.Tensor([0 0 0 0], shape=(4,), dtype=int32)
power :  tf.Tensor([    1    64  2187 65536], shape=(4,), dtype=int32)
